import React from 'react';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Mail, Phone } from 'lucide-react';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Separator } from '@/components/ui/separator';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-50 to-indigo-50 dark:from-gray-900 dark:to-purple-950">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <div className="mb-6">
          <Button variant="ghost" asChild>
            <Link to="/" className="flex items-center gap-2">
              <ArrowLeft className="h-4 w-4" />
              Back
            </Link>
          </Button>
        </div>

        <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-6 md:p-8">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
              Terms and Conditions
            </h1>
            <p className="text-xl text-primary font-medium">
              Study AI – Smart Learning Assistant
            </p>
          </div>
          
          <ScrollArea className="h-[70vh]">
            <div className="space-y-8 text-gray-700 dark:text-gray-300 pr-4">
              
              {/* Section 1 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  1. Acceptance of Terms
                </h2>
                <p>
                  By accessing or using Study AI, you agree to comply with these Terms and Conditions.
                  If you do not agree, please do not use the application.
                </p>
              </section>

              <Separator />

              {/* Section 2 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  2. Use of the Application
                </h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Study AI is provided for educational purposes only</li>
                  <li>Users must use the app responsibly and legally</li>
                  <li>Misuse, abuse, or attempt to exploit the app is strictly prohibited</li>
                </ul>
              </section>

              <Separator />

              {/* Section 3 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  3. AI-Generated Content
                </h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>All content generated by AI is for learning assistance only</li>
                  <li>Study AI does not guarantee absolute accuracy of AI-generated responses</li>
                  <li>Users are responsible for how they use the provided information</li>
                </ul>
              </section>

              <Separator />

              {/* Section 4 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  4. Advertisements
                </h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>The app may display third-party advertisements</li>
                  <li>Study AI is not responsible for third-party products or services shown in ads</li>
                  <li>Users interact with ads at their own discretion</li>
                </ul>
              </section>

              <Separator />

              {/* Section 5 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  5. Virtual Items
                </h2>
                <div className="bg-orange-50 dark:bg-orange-900/20 p-4 rounded-lg border-l-4 border-orange-500 mb-3">
                  <p className="font-medium text-orange-800 dark:text-orange-300">
                    Tokens and points are non-transferable virtual items with no monetary value.
                  </p>
                </div>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Tokens and points are non-transferable virtual items</li>
                  <li>They have no monetary value</li>
                  <li>Misuse or manipulation of the system may result in account restriction</li>
                </ul>
              </section>

              <Separator />

              {/* Section 6 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  6. Intellectual Property
                </h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>All app content, design, and branding belong to the Study AI Team</li>
                  <li>Unauthorized copying or misuse is prohibited</li>
                </ul>
              </section>

              <Separator />

              {/* Section 7 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  7. Limitation of Liability
                </h2>
                <p className="mb-3">Study AI is not liable for:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Any learning outcomes based on AI-generated content</li>
                  <li>Technical interruptions or data loss</li>
                  <li>Third-party services or advertisements</li>
                </ul>
              </section>

              <Separator />

              {/* Section 8 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  8. Modifications
                </h2>
                <p>
                  We reserve the right to modify these Terms at any time.
                  Continued use of the app implies acceptance of updated terms.
                </p>
              </section>

              <Separator />

              {/* Section 9 */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  9. Governing Law
                </h2>
                <p>
                  These Terms shall be governed by the laws of India.
                </p>
              </section>

              <Separator />

              {/* Section 10 - Contact */}
              <section>
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
                  10. Contact Information
                </h2>
                <p className="mb-4">For any questions regarding these Terms:</p>
                <div className="bg-gray-50 dark:bg-gray-700/50 p-4 rounded-lg space-y-3">
                  <div className="flex items-center gap-3">
                    <Mail className="h-5 w-5 text-primary" />
                    <a href="mailto:ajit91884270@gmail.com" className="text-primary hover:underline">
                      ajit91884270@gmail.com
                    </a>
                  </div>
                  <div className="flex items-center gap-3">
                    <Phone className="h-5 w-5 text-primary" />
                    <a href="tel:+919504797910" className="text-primary hover:underline">
                      +91-9504797910
                    </a>
                  </div>
                </div>
              </section>

              <div className="pt-6 text-center text-sm text-muted-foreground">
                <p>© 2026 Study AI. All rights reserved.</p>
              </div>
            </div>
          </ScrollArea>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
