
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
// Please run `npm install marked @types/marked` to add this required library.
import { marked } from 'marked';

/**
 * Pre-processes raw text, converts it to styled HTML, and renders it to a canvas.
 */
async function renderContentToCanvas(rawText: string, title?: string): Promise<HTMLCanvasElement> {
  // 1. Data Pre-processing: Remove metadata tags like <|source|>
  let content = rawText.replace(/<\\|.*?\\|>/g, '');

  // 2. Visual Formatting: Find special sections and wrap them for styling
  // Using a function to replace to avoid issues with nested content and ensure clean paragraphs.
  const replacer = (match: string, p1: string, p2: string) => {
    const boxType = p1.includes('💡') ? 'remember-box' : 'practice-box';
    const header = p1.includes('💡') ? '💡 Remember This' : '❓ Quick Practice';
    // Parse inner content as markdown
    const innerHtml = marked.parse(p2.trim()); 
    return `
      <div class="${boxType}">
        <h4>${header}</h4>
        ${innerHtml}
      </div>
    `;
  };
  content = content.replace(/(💡 Remember This:|❓ Quick Practice:)([\s\S]*?)(?=\\n\\n|💡|❓|$)/g, replacer);

  // 3. Convert the rest of the markdown to HTML using marked.js
  const htmlContent = marked.parse(content);
  
  // Create a temporary container for rendering
  const container = document.createElement('div');
  
  // Set A4 paper size and the requested 20mm margins
  // 1mm = 3.7795px. 20mm = ~76px.
  // A4 width = 210mm. Content area = 210 - 20 - 20 = 170mm.
  container.style.cssText = `
    position: fixed; left: -9999px; top: 0;
    width: 170mm; 
    padding: 0;
    margin: 20mm;
    background: white;
    font-family: 'Noto Sans', 'Noto Sans Devanagari', Arial, sans-serif;
    font-size: 14px;
    line-height: 1.7;
    color: #1a1a1a;
  `;

  const topicTitle = title || 'Study AI Notes';
  
  // 4. Visual Formatting Rules via a CSS <style> block
  const styles = `
    h3 {
      font-size: 16pt !important;
      font-weight: bold !important;
      color: #2563eb !important; /* Theme Blue */
      margin-top: 24px !important;
      margin-bottom: 12px !important;
    }
    strong {
      font-weight: 700; /* Emphasize bolded text */
    }
    .remember-box, .practice-box {
      background-color: #f1f5f9; /* Light Grey/Pale Blue */
      border-radius: 8px;
      padding: 12px 16px;
      margin: 16px 0;
    }
    .remember-box h4, .practice-box h4 {
      margin: 0 0 8px 0;
      font-weight: 700;
      color: #1e293b;
    }
    .remember-box p, .practice-box p {
      margin: 0;
    }
    ul, ol {
      padding-left: 20px;
    }
    p {
      margin-bottom: 12px;
    }
  `;

  // Inject fonts, styles, and content into the container
  container.innerHTML = `
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari:wght@400;700&family=Noto+Sans:wght@400;700&display=swap" rel="stylesheet">
    <style>${styles}</style>
    ${htmlContent}
  `;
  
  document.body.appendChild(container);

  // Wait for fonts and content to render
  await new Promise(resolve => setTimeout(resolve, 1000));

  const canvas = await html2canvas(container, {
    scale: 2, // Higher resolution
    useCORS: true,
    backgroundColor: '#ffffff',
  });

  document.body.removeChild(container);

  return canvas;
}

/** 
 * Generate a PDF document from chat content with proper metadata and formatting.
 */
export async function generateChatPdfAsync(content: string, title?: string): Promise<jsPDF> {
  const topicTitle = title || 'Study AI Generated Notes';
  const canvas = await renderContentToCanvas(content, topicTitle);

  const pdf = new jsPDF('p', 'mm', 'a4');
  
  // 5. PDF Metadata: Set the document title
  pdf.setProperties({
    title: topicTitle
  });

  const imgWidth = 210; // A4 width in mm
  const pageHeight = 297; // A4 height in mm
  const imgHeight = (canvas.height * imgWidth) / canvas.width;
  
  let heightLeft = imgHeight;
  let position = 0;

  // Add the rendered HTML as an image
  pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, 0, imgWidth, imgHeight);
  heightLeft -= pageHeight;

  // Add new pages if content overflows
  while (heightLeft > 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(canvas.toDataURL('image/png'), 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }
  
  // 6. PDF Metadata: Add a footer to every page
  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setFontSize(9);
    pdf.setTextColor('#888888');
    // Center the footer text
    pdf.text(
      'Generated by Study AI - Your Personal Learning Assistant.',
      pdf.internal.pageSize.getWidth() / 2,
      pageHeight - 10, // 10mm from the bottom
      { align: 'center' }
    );
  }

  return pdf;
}

/** Download chat content as PDF */
export async function downloadChatPdf(content: string, title?: string) {
  const { safeDownload } = await import('./webviewDownload');
  const doc = await generateChatPdfAsync(content, title);
  const blob = doc.output('blob');
  const fileName = `${(title || 'Study-AI-Notes').replace(/\\s+/g, '-')}.pdf`;
  await safeDownload({ blob, filename: fileName, mimeType: 'application/pdf' });
}

/** Share chat content as PDF (with fallback to download) */
export async function shareChatPdf(content:string, title?: string) {
  const { safeDownload } = await import('./webviewDownload');
  const doc = await generateChatPdfAsync(content, title);
  const blob = doc.output('blob');
  const fileName = `${(title || 'Study-AI-Notes').replace(/\\s+/g, '-')}.pdf`;

  try {
    const file = new File([blob], fileName, { type: 'application/pdf' });
    if (navigator.share && navigator.canShare?.({ files: [file] })) {
      await navigator.share({ title: title || 'Study AI Notes', files: [file] });
      return true;
    }
  } catch { /* fallback */ }

  await safeDownload({ blob, filename: fileName, mimeType: 'application/pdf' });
  return false;
}
