// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { SupabaseClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const SUPABASE_REQUEST_TIMEOUT_MS = 20000;
let supabaseClientRef: SupabaseClient<Database> | null = null;

const isEdgeFunctionRequest = (input: RequestInfo | URL): boolean => {
  const url = typeof input === 'string'
    ? input
    : input instanceof URL
      ? input.toString()
      : input.url;

  return url.includes('/functions/v1/');
};

const fetchWithTimeout: typeof fetch = async (input, init) => {
  const requestInit: RequestInit = {
    ...init,
  };

  const isEdgeCall = isEdgeFunctionRequest(input);
  if (isEdgeCall && supabaseClientRef) {
    await supabaseClientRef.auth.getSession();
  }

  const hasExternalSignal = Boolean(init?.signal);
  if (hasExternalSignal) {
    return fetch(input, requestInit);
  }

  const controller = new AbortController();
  const timeoutId = window.setTimeout(() => controller.abort(), SUPABASE_REQUEST_TIMEOUT_MS);

  try {
    let response = await fetch(input, {
      ...requestInit,
      signal: controller.signal,
    });

    if (
      isEdgeCall
      && supabaseClientRef
      && (response.status === 401 || response.status === 403)
    ) {
      const { data } = await supabaseClientRef.auth.refreshSession();
      if (data.session) {
        response = await fetch(input, {
          ...requestInit,
          signal: controller.signal,
        });
      }
    }

    return response;
  } finally {
    window.clearTimeout(timeoutId);
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: fetchWithTimeout,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});

supabaseClientRef = supabase;
